name: Receive Webhook from Repository B 

on:
  repository_dispatch:
    types:
      - repoB-push

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository A
      uses: actions/checkout@v2

    - name: Update Content from Repository B
      run: |
        rm -fr content
        git clone https://github.com/justakazh/technical_notes content && rm -rf content/.git content/.github
