name: Receive Webhook from Repository B 

on:
  repository_dispatch:
    types:
      - repoB-push

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository A
      uses: actions/checkout@v2

    - name: Update Content from Repository B
      run: |
        git config --global user.email "bot@github.com"
        git config --global user.name "github [bot]"
        rm -fr content
        git clone https://github.com/justakazh/technical_notes content && rm -rf content/.git content/.github
        git add .
        git commit -m "new update"
        git push origin main
